export const categoryCopy: Record<string, { tagline: string; intro: string; perfectFor: string[]; tip: string }> = {
  "fashion-lifestyle": {
    tagline: "Style they choose themselves",
    intro: "Fashion is personal — sizes, fits, colours and trends vary for everyone. Fashion and lifestyle e-gift cards from brands like Lifestyle, Westside, Pantaloons, Van Heusen, Allen Solly and Fabindia let your loved ones pick the outfit that feels like them, from festive ethnic wear to office formals and weekend casuals.",
    perfectFor: ["Birthdays", "Diwali & Eid shopping", "Graduations", "Colleague farewells"],
    tip: "Check whether the card is valid online, in-store or both — many fashion brands accept cards across their stores nationwide.",
  },
  "e-commerce": {
    tagline: "Millions of products, one gift card",
    intro: "Marketplace e-gift cards are the most flexible gift you can give. With Amazon, Flipkart, Myntra, AJIO and Tata CLiQ cards, recipients can shop across electronics, fashion, home, books and more — making them the safest pick when you don't know someone's exact taste.",
    perfectFor: ["People who have everything", "Last-minute gifts", "Festive sales", "Employee rewards"],
    tip: "Marketplace vouchers are usually added to the recipient's account wallet, so they can use the balance across multiple orders.",
  },
  "food-dining": {
    tagline: "Treats, feasts and coffee runs",
    intro: "Nothing says 'thinking of you' like a great meal. Food and dining gift cards from Swiggy, Zomato, Starbucks, Domino's, KFC, McDonald's, Barbeque Nation and Behrouz Biryani turn an ordinary evening into a celebration — at home or at their favourite restaurant.",
    perfectFor: ["Thank-you gifts", "Work-from-home teams", "Students", "Movie-night combos"],
    tip: "Delivery app cards work across thousands of restaurants, while restaurant-brand cards are perfect for fans of a specific chain.",
  },
  travel: {
    tagline: "Gift the next adventure",
    intro: "Travel gift cards from MakeMyTrip, Cleartrip, Yatra, EaseMyTrip, SpiceJet, Air India and Uber help people take the trip they keep postponing — flights, hotels, holiday packages, trains, buses and cabs, all covered.",
    perfectFor: ["Honeymoons", "Retirement gifts", "Anniversaries", "Wanderlust friends"],
    tip: "Travel cards often have specific validity and usage rules for flights vs hotels — read the brand terms before gifting for a planned trip.",
  },
  jewellery: {
    tagline: "Timeless gifts that shine",
    intro: "Jewellery e-gift cards from Tanishq, Kalyan Jewellers, Malabar Gold, Joyalukkas, BlueStone, Giva and more let recipients choose their perfect piece or invest in gold coins — ideal for weddings, anniversaries, Dhanteras and milestone birthdays.",
    perfectFor: ["Weddings", "Dhanteras & Akshaya Tritiya", "Anniversaries", "Mother's Day"],
    tip: "Many jewellery brands allow multiple gift cards per bill, and some cards are specific to gold coins, diamond or studded jewellery — pick the right variant.",
  },
  electronics: {
    tagline: "Upgrade their tech",
    intro: "Gadgets are wish-list toppers. Electronics gift cards from Croma, Reliance Digital, Samsung, Vijay Sales and Apple premium resellers let people put the value towards a new phone, headphones, laptop or smart-home device.",
    perfectFor: ["Graduations", "Work anniversaries", "Tech lovers", "Diwali"],
    tip: "Electronics prices are high — a gift card is a thoughtful contribution towards a bigger purchase the recipient is already planning.",
  },
  "home-needs": {
    tagline: "Everyday essentials, sorted",
    intro: "Grocery and home-needs gift cards from BigBasket, Reliance Smart, Spencer's, Nature's Basket and More help families stock up on daily essentials — a practical, genuinely appreciated gift for new parents, new homes and festive seasons.",
    perfectFor: ["House warmings", "New parents", "Festive hampers", "Support for loved ones"],
    tip: "Grocery cards are one of the most practical gifts you can send — they're used within days.",
  },
  "home-furnishings": {
    tagline: "Make a house feel like home",
    intro: "Furniture and decor gift cards from Pepperfry, Urban Ladder, Home Centre, IKEA, Wakefit and Nilkamal are the perfect contribution to a new home or a room makeover — without guessing someone's interior style.",
    perfectFor: ["Weddings", "House warmings", "Griha pravesh", "Moving abroad"],
    tip: "Pool together with friends for a higher-value furniture card — it's a gift the couple will use every day.",
  },
  "health-beauty": {
    tagline: "Self-care, gifted",
    intro: "Beauty and wellness gift cards from Nykaa, Mamaearth, The Body Shop, Kiehl's, MyGlamm, Healthians and HealthKart let people pamper themselves with skincare, makeup, fragrance, supplements and health check-ups.",
    perfectFor: ["Rakhi", "Mother's Day", "Birthdays", "Wellness rewards"],
    tip: "Beauty is highly personal — a gift card lets them choose shades and skin types that suit them.",
  },
  entertainment: {
    tagline: "Movies, shows and nights out",
    intro: "Entertainment gift cards from BookMyShow and PVR INOX are made for movie nights, concerts, plays and live events — a fun, experience-first gift for friends, couples and teams.",
    perfectFor: ["Date nights", "Teen birthdays", "Team outings", "Valentine's Day"],
    tip: "Combine a movie card with a food delivery or café card for a complete night out.",
  },
  gaming: {
    tagline: "Level up their game",
    intro: "Gaming gift cards for Steam, Valorant Points and UniPin let gamers buy new titles, in-game currency, skins and passes — the one gift gamers never return.",
    perfectFor: ["Teen birthdays", "Exam results", "Gamer friends", "Esports rewards"],
    tip: "Confirm the gaming platform and region before gifting — in-game currencies are platform-specific.",
  },
  hospitality: {
    tagline: "Stays and experiences to remember",
    intro: "Hotel, spa and fine-dining gift cards from Taj, ITC Hotels, Marriott, Oberoi, Hyatt and The Postcard Hotels turn a gift into a memory — a luxurious staycation, a spa afternoon or a celebratory dinner.",
    perfectFor: ["Anniversaries", "Parents' milestones", "Honeymoons", "Leadership awards"],
    tip: "Hotel cards may have blackout dates and advance-booking rules — share the terms with the recipient.",
  },
  "international-brands": {
    tagline: "Global labels, gifted locally",
    intro: "International brand gift cards — from Coach, Michael Kors, Hugo Boss, Tumi and Kate Spade to Levi's, Superdry, Skechers and Starbucks — are perfect when you want a gift that feels premium and aspirational.",
    perfectFor: ["Milestone birthdays", "Promotions", "Luxury lovers", "Corporate leadership gifts"],
    tip: "Premium brands often work in-store at select locations — check the store list in the brand terms.",
  },
  "sportswear-footwear": {
    tagline: "For the active and the sneakerheads",
    intro: "Sports and footwear gift cards from Decathlon, Puma, Skechers, Speedo, Wildcraft and Birkenstock support fitness goals, weekend treks and sneaker collections alike.",
    perfectFor: ["New Year resolutions", "Marathon finishers", "Teen birthdays", "Wellness programs"],
    tip: "Shoe sizes vary across brands — a gift card lets them try before they buy.",
  },
  subscriptions: {
    tagline: "Gifts that keep on giving",
    intro: "Subscription gift cards for Amazon Prime, Sony LIV, Epic On, FanCode, HealthifyMe and Cult give months of entertainment, sport, learning and fitness — a gift they'll think of you every time they use it.",
    perfectFor: ["Long-distance friends", "Parents", "Sports fans", "Fitness goals"],
    tip: "Subscription cards usually have fixed plan durations — choose the plan length that suits the recipient.",
  },
  "baby-products": {
    tagline: "Welcome the little ones",
    intro: "Baby and kids gift cards from FirstCry, Mothercare, MiniKlub and Hamleys help new parents pick exactly what they need — clothes in the right size, diapers, toys and nursery essentials.",
    perfectFor: ["Baby showers", "Naming ceremonies", "First birthdays", "New parents at work"],
    tip: "Babies outgrow clothes fast — gift cards let parents buy the right size at the right time.",
  },
  books: {
    tagline: "Stories and knowledge",
    intro: "Book gift cards let readers explore new authors, textbooks and bestsellers at their own pace — ideal for students, teachers and lifelong learners.",
    perfectFor: ["Students", "Teachers' Day", "Book clubs", "Retirement"],
    tip: "Pair a book card with a note recommending a book you loved.",
  },
  "finance-insurance": {
    tagline: "Flexible value, smart gifting",
    intro: "Payment wallet and giving cards such as Amazon Pay, PhonePe and donation vouchers offer maximum flexibility — use the balance across many merchants, or donate to a cause close to the heart.",
    perfectFor: ["Flexible gifting", "Cause-based gifting", "Cashback-style rewards", "Anyone, anytime"],
    tip: "Wallet-style cards may have KYC or usage limits set by the issuer — check the terms.",
  },
};
